apiVersion: v1
kind: Service
metadata:
  annotations:
      metallb.universe.tf/allow-shared-ip: metallb
  name: ftps
  labels:
      app: ftps
spec:
  ports:
  - port: 21
    targetPort: 21
    protocol: TCP
    name: port-21
  - port: 30000
    targetPort: 30000
    protocol: TCP
    name: port-30000
  selector:
    app: ftps
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30000
